import { v4 as uuidv4 } from "uuid"
import type { Recipe } from "./types"

export const initialRecipes: Recipe[] = [
  {
    id: uuidv4(),
    name: "Chocolat à base de baie de goji sucré avec de la stévia",
    description: "Un délicieux chocolat noir enrichi de baies de goji et sucré à la stévia.",
    ingredients: [
      { name: "Pâte de chocolat noir 100%", quantity: 97, price: 100000 },
      { name: "Extrait de stévia", quantity: 0.5, price: 600000 },
      { name: "Baie de goji", quantity: 15, price: 160000 },
      { name: "Poudre de baobab", quantity: 1.5, price: 240000 },
      { name: "Jus de citron", quantity: 0.05, price: 32000 },
      { name: "Zeste de citron", quantity: 0.3, price: 60000 },
    ],
    protocol: [
      "Peser 0,5 g d'extrait de stévia.",
      "Ajouter 97 g de pâte de chocolat fondu.",
      "Incorporer le jus et le zeste de citron.",
      "Bien mélanger jusqu'à obtenir une texture homogène.",
      "Laisser refroidir la pâte sur un plan de travail en marbre jusqu'à atteindre 28°C.",
      "Verser le mélange dans des moules.",
      "Ajouter les baies de goji sur le dessus ou les incorporer légèrement.",
      "Placer les moules dans une chambre froide ou au réfrigérateur jusqu'à solidification complète.",
    ],
    molding: [],
    yield: 15,
    totalCost: 12600,
    stock: 10,
  },
  {
    id: uuidv4(),
    name: "Chocolat à la poudre d'amande et sucré à la stévia",
    description: "Un chocolat onctueux à la poudre d'amande, parfaitement équilibré.",
    ingredients: [
      { name: "Pâte de chocolat noir 100%", quantity: 89, price: 100000 },
      { name: "Extrait de stévia", quantity: 0.3, price: 600000 },
      { name: "Poudre d'amande", quantity: 10, price: 80000 },
      { name: "Jus de citron", quantity: 0.05, price: 32000 },
      { name: "Zeste de citron", quantity: 0.3, price: 60000 },
    ],
    protocol: [
      "Peser 0,3 g d'extrait de stévia.",
      "Ajouter 89 g de pâte de chocolat fondu.",
      "Incorporer 10 g de poudre d'amande.",
      "Ajouter le jus et le zeste de citron.",
      "Bien mélanger jusqu'à obtenir une texture homogène.",
      "Laisser refroidir la pâte sur un plan de travail en marbre jusqu'à atteindre 28°C.",
      "Verser le mélange dans des moules.",
      "Placer les moules dans une chambre froide ou au réfrigérateur jusqu'à solidification complète.",
    ],
    molding: [],
    yield: 20,
    totalCost: 10800,
    stock: 15,
  },
  {
    id: uuidv4(),
    name: "Chocolat sucré à la stévia avec une pincée de sel",
    description: "L'alliance parfaite du chocolat noir, de la stévia et d'une touche de sel.",
    ingredients: [
      { name: "Pâte de chocolat noir 100%", quantity: 98, price: 100000 },
      { name: "Extrait de stévia", quantity: 0.5, price: 600000 },
      { name: "Sel", quantity: 0.5, price: 20000 },
      { name: "Jus de citron", quantity: 0.05, price: 32000 },
      { name: "Zeste de citron", quantity: 0.5, price: 60000 },
    ],
    protocol: [
      "Peser 0,5 g d'extrait de stévia.",
      "Ajouter 98 g de pâte de chocolat fondu.",
      "Incorporer une pincée de sel.",
      "Ajouter le jus et le zeste de citron.",
      "Mélanger soigneusement jusqu'à obtenir une texture homogène.",
      "Laisser refroidir la pâte sur un plan de travail en marbre jusqu'à atteindre 28°C.",
      "Verser le mélange dans des moules.",
      "Placer les moules dans une chambre froide ou au réfrigérateur jusqu'à solidification complète.",
    ],
    molding: [],
    yield: 38,
    totalCost: 11400,
    stock: 25,
  },
]
